% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={ArbolesDeDecision},
  pdfauthor={Cristopher Barrios, Carlos Daniel Estrada},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{ArbolesDeDecision}
\author{Cristopher Barrios, Carlos Daniel Estrada}
\date{2023-03-10}

\begin{document}
\maketitle

librerias

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(rpart)}
\FunctionTok{library}\NormalTok{(rpart.plot)}
\FunctionTok{library}\NormalTok{(dplyr) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(fpc) }
\FunctionTok{library}\NormalTok{(cluster) }
\FunctionTok{library}\NormalTok{(}\StringTok{"ggpubr"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(mclust)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Package 'mclust' version 6.0.0
## Type 'citation("mclust")' for citing this R package in publications.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: lattice
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tree)}
\FunctionTok{library}\NormalTok{(randomForest)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## randomForest 4.7-1.1
\end{verbatim}

\begin{verbatim}
## Type rfNews() to see new features/changes/bug fixes.
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'randomForest'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:ggplot2':
## 
##     margin
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     combine
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(plyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ------------------------------------------------------------------------------
\end{verbatim}

\begin{verbatim}
## You have loaded plyr after dplyr - this is likely to cause problems.
## If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
## library(plyr); library(dplyr)
\end{verbatim}

\begin{verbatim}
## ------------------------------------------------------------------------------
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'plyr'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:ggpubr':
## 
##     mutate
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:dplyr':
## 
##     arrange, count, desc, failwith, id, mutate, rename, summarise,
##     summarize
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(}\StringTok{"stats"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"datasets"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"prediction"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v forcats   1.0.0     v stringr   1.5.0
## v lubridate 1.9.2     v tibble    3.1.8
## v purrr     1.0.1     v tidyr     1.3.0
## v readr     2.1.4
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x plyr::arrange()         masks dplyr::arrange()
## x randomForest::combine() masks dplyr::combine()
## x purrr::compact()        masks plyr::compact()
## x plyr::count()           masks dplyr::count()
## x plyr::desc()            masks dplyr::desc()
## x plyr::failwith()        masks dplyr::failwith()
## x dplyr::filter()         masks stats::filter()
## x plyr::id()              masks dplyr::id()
## x dplyr::lag()            masks stats::lag()
## x purrr::lift()           masks caret::lift()
## x purrr::map()            masks mclust::map()
## x randomForest::margin()  masks ggplot2::margin()
## x plyr::mutate()          masks ggpubr::mutate(), dplyr::mutate()
## x plyr::rename()          masks dplyr::rename()
## x plyr::summarise()       masks dplyr::summarise()
## x plyr::summarize()       masks dplyr::summarize()
## i Use the ]8;;http://conflicted.r-lib.org/conflicted package]8;; to force all conflicts to become errors
\end{verbatim}

\hypertarget{use-los-mismos-conjuntos-de-entrenamiento-y-prueba-que-usuxf3-para-los-uxe1rboles-de-decisiuxf3n-en-la-hoja-de-trabajo-anterior.}{%
\subsubsection{1. Use los mismos conjuntos de entrenamiento y prueba que
usó para los árboles de decisión en la hoja de trabajo
anterior.}\label{use-los-mismos-conjuntos-de-entrenamiento-y-prueba-que-usuxf3-para-los-uxe1rboles-de-decisiuxf3n-en-la-hoja-de-trabajo-anterior.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos }\OtherTok{=} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"./train.csv"}\NormalTok{)}
\NormalTok{test}\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"./test.csv"}\NormalTok{, }\AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Lo Realizado anteriormente:

Inciso 4

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{set\_entrenamiento }\OtherTok{\textless{}{-}} \FunctionTok{sample\_frac}\NormalTok{(datos, .}\DecValTok{7}\NormalTok{)}
\NormalTok{set\_prueba }\OtherTok{\textless{}{-}}\FunctionTok{setdiff}\NormalTok{(datos, set\_entrenamiento)}


\NormalTok{drop }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"LotFrontage"}\NormalTok{, }\StringTok{"Alley"}\NormalTok{, }\StringTok{"MasVnrType"}\NormalTok{, }\StringTok{"MasVnrArea"}\NormalTok{, }\StringTok{"BsmtQual"}\NormalTok{, }\StringTok{"BsmtCond"}\NormalTok{, }\StringTok{"BsmtExposure"}\NormalTok{, }\StringTok{"BsmtFinType1"}\NormalTok{, }\StringTok{"BsmtFinType2"}\NormalTok{, }\StringTok{"Electrical"}\NormalTok{, }\StringTok{"FireplaceQu"}\NormalTok{, }\StringTok{"GarageType"}\NormalTok{, }\StringTok{"GarageYrBlt"}\NormalTok{, }\StringTok{"GarageFinish"}\NormalTok{, }\StringTok{"GarageQual"}\NormalTok{, }\StringTok{"GarageCond"}\NormalTok{, }\StringTok{"PoolQC"}\NormalTok{, }\StringTok{"Fence"}\NormalTok{, }\StringTok{"MiscFeature"}\NormalTok{)}
\NormalTok{set\_entrenamiento }\OtherTok{\textless{}{-}}\NormalTok{ set\_entrenamiento[, }\SpecialCharTok{!}\NormalTok{(}\FunctionTok{names}\NormalTok{(set\_entrenamiento) }\SpecialCharTok{\%in\%}\NormalTok{ drop)]}
\NormalTok{set\_prueba }\OtherTok{\textless{}{-}}\NormalTok{ set\_prueba[, }\SpecialCharTok{!}\NormalTok{(}\FunctionTok{names}\NormalTok{(set\_prueba) }\SpecialCharTok{\%in\%}\NormalTok{ drop)]}
\end{Highlighting}
\end{Shaded}

\hypertarget{elabore-un-uxe1rbol-de-regresiuxf3n-para-predecir-el-precio-de-las-casas-usando-todas-las-variables.}{%
\subsubsection{2. Elabore un árbol de regresión para predecir el precio
de las casas usando todas las
variables.}\label{elabore-un-uxe1rbol-de-regresiuxf3n-para-predecir-el-precio-de-las-casas-usando-todas-las-variables.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol\_3 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(SalePrice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_entrenamiento)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prp}\NormalTok{(arbol\_3, }\AttributeTok{main=}\StringTok{"Arbol de Regresion"}\NormalTok{, }\AttributeTok{nn=}\ConstantTok{TRUE}\NormalTok{, }\AttributeTok{fallen.leaves =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{shadow.col =} \StringTok{"green"}\NormalTok{, }\AttributeTok{branch.lty =} \DecValTok{3}\NormalTok{, }\AttributeTok{branch =}\NormalTok{ .}\DecValTok{5}\NormalTok{, }\AttributeTok{faclen =} \DecValTok{0}\NormalTok{, }\AttributeTok{trace =} \DecValTok{1}\NormalTok{, }\AttributeTok{split.cex =} \FloatTok{0.8}\NormalTok{, }\AttributeTok{split.box.col =} \StringTok{"lightblue"}\NormalTok{, }\AttributeTok{split.border.col =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{split.round =} \FloatTok{0.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## cex 1   xlim c(0, 1)   ylim c(0, 1)
\end{verbatim}

\includegraphics{ArbolesDeDecision_files/figure-latex/unnamed-chunk-5-1.pdf}

--modelo del arbol de decision

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#arbolModelo1 \textless{}{-} rpart(SalePrice\textasciitilde{}.,set\_prueba,method = "class")}
\CommentTok{\#rpart.plot(arbolModelo1)}
\end{Highlighting}
\end{Shaded}

Como se puede observar, el arbol utilza las variables que consideramos
esenciales para predecir el valor de una casa

\hypertarget{uxfaselo-para-predecir-y-analice-el-resultado.-quuxe9-tal-lo-hizo}{%
\subsubsection{3. Úselo para predecir y analice el resultado. ¿Qué tal
lo
hizo?}\label{uxfaselo-para-predecir-y-analice-el-resultado.-quuxe9-tal-lo-hizo}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicciones }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbol\_3, }\AttributeTok{data =}\NormalTok{ set\_prueba)}

\NormalTok{mse }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((predicciones }\SpecialCharTok{{-}}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}\SpecialCharTok{**}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predicciones - set_prueba$SalePrice: longitud de objeto mayor no es
## múltiplo de la longitud de uno menor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10000014148
\end{verbatim}

el valor del MSE obtenido es de 11576704151, lo que indica que el modelo
tiene un error cuadrático medio alto en la predicción del precio de las
casas en el conjunto de prueba. Por lo tanto, el modelo no es muy
preciso en la predicción del precio de las casas y puede requerir más
ajustes y mejoras.

\hypertarget{haga-al-menos-3-modelos-muxe1s-cambiando-el-paruxe1metro-de-la-profundidad-del-uxe1rbol.-cuuxe1l-es-el-mejor-modelo-para-predecir-el-precio-de-las-casas}{%
\subsubsection{4. Haga, al menos, 3 modelos más cambiando el parámetro
de la profundidad del árbol. ¿Cuál es el mejor modelo para predecir el
precio de las
casas?}\label{haga-al-menos-3-modelos-muxe1s-cambiando-el-paruxe1metro-de-la-profundidad-del-uxe1rbol.-cuuxe1l-es-el-mejor-modelo-para-predecir-el-precio-de-las-casas}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol\_4 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(SalePrice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_entrenamiento, }\AttributeTok{control =} \FunctionTok{rpart.control}\NormalTok{(}\AttributeTok{maxdepth =} \DecValTok{5}\NormalTok{))}
\NormalTok{predicciones2 }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbol\_4, }\AttributeTok{data =}\NormalTok{ set\_prueba)}

\NormalTok{mse2 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((predicciones2 }\SpecialCharTok{{-}}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}\SpecialCharTok{**}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predicciones2 - set_prueba$SalePrice: longitud de objeto mayor no es
## múltiplo de la longitud de uno menor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10000014148
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol\_5 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(SalePrice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_entrenamiento, }\AttributeTok{control =} \FunctionTok{rpart.control}\NormalTok{(}\AttributeTok{maxdepth =} \DecValTok{10}\NormalTok{))}
\NormalTok{predicciones3 }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbol\_5, }\AttributeTok{data =}\NormalTok{ set\_prueba)}

\NormalTok{mse3 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((predicciones3 }\SpecialCharTok{{-}}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}\SpecialCharTok{**}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predicciones3 - set_prueba$SalePrice: longitud de objeto mayor no es
## múltiplo de la longitud de uno menor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10000014148
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol\_6 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(SalePrice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_entrenamiento, }\AttributeTok{control =} \FunctionTok{rpart.control}\NormalTok{(}\AttributeTok{maxdepth =} \DecValTok{15}\NormalTok{))}
\NormalTok{predicciones4 }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbol\_6, }\AttributeTok{data =}\NormalTok{ set\_prueba)}

\NormalTok{mse4 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((predicciones4 }\SpecialCharTok{{-}}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}\SpecialCharTok{**}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predicciones4 - set_prueba$SalePrice: longitud de objeto mayor no es
## múltiplo de la longitud de uno menor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10000014148
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol\_6 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(SalePrice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_entrenamiento, }\AttributeTok{control =} \FunctionTok{rpart.control}\NormalTok{(}\AttributeTok{maxdepth =} \DecValTok{3}\NormalTok{))}
\NormalTok{predicciones4 }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbol\_6, }\AttributeTok{data =}\NormalTok{ set\_prueba)}

\NormalTok{mse4 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{((predicciones4 }\SpecialCharTok{{-}}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}\SpecialCharTok{**}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in predicciones4 - set_prueba$SalePrice: longitud de objeto mayor no es
## múltiplo de la longitud de uno menor
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mse4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9970951565
\end{verbatim}

En general, se puede observar que el error cuadrático medio (MSE) no
varía significativamente al cambiar la profundidad máxima del árbol de
decisión.

El primer modelo que se ajusta con una profundidad máxima de 5, el
segundo modelo con una profundidad máxima de 10, el tercer modelo con
una profundidad máxima de 15, y el cuarto modelo con una profundidad
máxima de 3.

Se puede observar que el modelo con una profundidad máxima de 3, produce
un MSE ligeramente menor que los otros modelos, por lo tanto se podria
decir que este es el mejor. Sin embargo, este resultado debe tomarse con
precaución, ya que un modelo demasiado simple puede llevar a una
subestimación de la complejidad de los datos y, por lo tanto, a una
menor precisión en las predicciones.

\hypertarget{compare-los-resultados-con-el-modelo-de-regresiuxf3n-lineal-de-la-hoja-anterior-cuuxe1l-lo-hizo-mejor}{%
\subsubsection{5. Compare los resultados con el modelo de regresión
lineal de la hoja anterior, ¿cuál lo hizo
mejor?}\label{compare-los-resultados-con-el-modelo-de-regresiuxf3n-lineal-de-la-hoja-anterior-cuuxe1l-lo-hizo-mejor}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{porciento }\OtherTok{\textless{}{-}} \DecValTok{70}\SpecialCharTok{/}\DecValTok{100}
\NormalTok{datos}\SpecialCharTok{$}\NormalTok{clasificacion }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{SalePrice }\SpecialCharTok{\textless{}=} \DecValTok{251000}\NormalTok{, }\StringTok{"Economicas"}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{SalePrice }\SpecialCharTok{\textless{}=} \DecValTok{538000}\NormalTok{, }\StringTok{"Intermedias"}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{SalePrice }\SpecialCharTok{\textless{}=} \DecValTok{755000}\NormalTok{, }\StringTok{"Caras"}\NormalTok{)))}

\NormalTok{datos}\SpecialCharTok{$}\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{factor}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{clasificacion))}
\NormalTok{datosCC }\OtherTok{\textless{}{-}}\NormalTok{ datos[,}\FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{18}\NormalTok{,}\DecValTok{19}\NormalTok{,}\DecValTok{20}\NormalTok{,}\DecValTok{21}\NormalTok{,}\DecValTok{27}\NormalTok{,}\DecValTok{35}\NormalTok{,}\DecValTok{37}\NormalTok{,}\DecValTok{38}\NormalTok{,}\DecValTok{39}\NormalTok{,}\DecValTok{44}\NormalTok{,}\DecValTok{45}\NormalTok{,}\DecValTok{46}\NormalTok{,}\DecValTok{47}\NormalTok{,}\DecValTok{48}\NormalTok{,}\DecValTok{49}\NormalTok{,}\DecValTok{50}\NormalTok{,}\DecValTok{51}\NormalTok{,}\DecValTok{52}\NormalTok{,}\DecValTok{53}\NormalTok{,}\DecValTok{55}\NormalTok{,}\DecValTok{57}\NormalTok{,}\DecValTok{60}\NormalTok{,}\DecValTok{62}\NormalTok{,}\DecValTok{63}\NormalTok{,}\DecValTok{67}\NormalTok{,}\DecValTok{68}\NormalTok{,}\DecValTok{69}\NormalTok{,}\DecValTok{70}\NormalTok{,}\DecValTok{71}\NormalTok{,}\DecValTok{72}\NormalTok{,}\DecValTok{76}\NormalTok{,}\DecValTok{77}\NormalTok{,}\DecValTok{78}\NormalTok{,}\DecValTok{81}\NormalTok{,}\DecValTok{83}\NormalTok{)]}
\NormalTok{datosCC }\OtherTok{\textless{}{-}}\NormalTok{ datosCC[,}\FunctionTok{colSums}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(datosCC))}\SpecialCharTok{==}\DecValTok{0}\NormalTok{]}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}
\NormalTok{trainRowsNumber}\OtherTok{\textless{}{-}}\FunctionTok{sample}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(datosCC),porciento}\SpecialCharTok{*}\FunctionTok{nrow}\NormalTok{(datosCC))}
\NormalTok{train}\OtherTok{\textless{}{-}}\NormalTok{datosCC[trainRowsNumber,]}
\NormalTok{test}\OtherTok{\textless{}{-}}\NormalTok{datosCC[}\SpecialCharTok{{-}}\NormalTok{trainRowsNumber,]}

\NormalTok{fitLM}\OtherTok{\textless{}{-}}\FunctionTok{lm}\NormalTok{(SalePrice}\SpecialCharTok{\textasciitilde{}}\NormalTok{., }\AttributeTok{data =}\NormalTok{ train) }
\FunctionTok{summary}\NormalTok{(fitLM)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = SalePrice ~ ., data = train)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -409357  -13924   -1521   11097  356054 
## 
## Coefficients: (2 not defined because of singularities)
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   -4.064e+05  1.717e+06  -0.237 0.812984    
## MSSubClass    -1.520e+02  3.248e+01  -4.680 3.26e-06 ***
## OverallQual    1.523e+04  1.494e+03  10.196  < 2e-16 ***
## OverallCond    4.302e+03  1.271e+03   3.386 0.000737 ***
## YearBuilt      3.472e+02  7.624e+01   4.553 5.94e-06 ***
## YearRemodAdd   1.128e+02  8.110e+01   1.391 0.164565    
## BsmtFinSF1     1.868e+01  5.805e+00   3.218 0.001331 ** 
## BsmtFinSF2     8.863e+00  8.865e+00   1.000 0.317656    
## BsmtUnfSF      7.719e+00  5.330e+00   1.448 0.147847    
## TotalBsmtSF           NA         NA      NA       NA    
## X1stFlrSF      4.513e+01  7.292e+00   6.188 8.89e-10 ***
## X2ndFlrSF      4.172e+01  6.006e+00   6.946 6.81e-12 ***
## LowQualFinSF   3.158e+01  2.310e+01   1.368 0.171753    
## GrLivArea             NA         NA      NA       NA    
## BsmtFullBath   6.811e+03  3.198e+03   2.130 0.033430 *  
## BsmtHalfBath   9.361e+03  5.365e+03   1.745 0.081329 .  
## FullBath       5.713e+03  3.515e+03   1.625 0.104417    
## HalfBath      -1.497e+02  3.257e+03  -0.046 0.963340    
## BedroomAbvGr  -9.937e+03  2.087e+03  -4.762 2.20e-06 ***
## KitchenAbvGr  -1.536e+04  6.372e+03  -2.410 0.016134 *  
## TotRmsAbvGrd   5.698e+03  1.528e+03   3.730 0.000203 ***
## Fireplaces     4.313e+03  2.144e+03   2.012 0.044530 *  
## GarageCars     1.217e+04  3.478e+03   3.498 0.000490 ***
## GarageArea    -1.132e+01  1.166e+01  -0.971 0.331910    
## WoodDeckSF     2.184e+01  9.935e+00   2.198 0.028178 *  
## OpenPorchSF   -2.412e+01  1.853e+01  -1.302 0.193369    
## EnclosedPorch  1.174e+01  2.133e+01   0.550 0.582223    
## X3SsnPorch     3.492e+01  3.496e+01   0.999 0.318074    
## ScreenPorch    4.727e+01  2.126e+01   2.224 0.026395 *  
## PoolArea      -6.411e-01  3.308e+01  -0.019 0.984540    
## MiscVal        2.427e-02  2.144e+00   0.011 0.990970    
## MoSold        -2.243e+02  4.264e+02  -0.526 0.599008    
## YrSold        -3.044e+02  8.539e+02  -0.356 0.721578    
## y              3.591e+04  3.874e+03   9.270  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 35520 on 989 degrees of freedom
## Multiple R-squared:  0.8068, Adjusted R-squared:  0.8007 
## F-statistic: 133.2 on 31 and 989 DF,  p-value: < 2.2e-16
\end{verbatim}

Los arboles de decisión se aproximan más al valor real de los inmuebles
que el modelo de regresión lineal

\hypertarget{dependiendo-del-anuxe1lisis-exploratorio-elaborado-cree-una-variable-respuesta-que-le-permita-clasificar-las-casas-en-econuxf3micas-intermedias-o-caras.-los-luxedmites-de-estas-clases-deben-tener-un-fundamento-en-la-distribuciuxf3n-de-los-datos-de-precios-y-estar-bien-explicados}{%
\subsubsection{6. Dependiendo del análisis exploratorio elaborado cree
una variable respuesta que le permita clasificar las casas en
Económicas, Intermedias o Caras. Los límites de estas clases deben tener
un fundamento en la distribución de los datos de precios, y estar bien
explicados}\label{dependiendo-del-anuxe1lisis-exploratorio-elaborado-cree-una-variable-respuesta-que-le-permita-clasificar-las-casas-en-econuxf3micas-intermedias-o-caras.-los-luxedmites-de-estas-clases-deben-tener-un-fundamento-en-la-distribuciuxf3n-de-los-datos-de-precios-y-estar-bien-explicados}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos}\SpecialCharTok{$}\NormalTok{clasificacion }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{SalePrice }\SpecialCharTok{\textgreater{}} \DecValTok{290000}\NormalTok{, }\StringTok{"Caras"}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{SalePrice}\SpecialCharTok{\textgreater{}}\DecValTok{170000}\NormalTok{, }\StringTok{"Intemedia"}\NormalTok{, }\StringTok{"Economicas"}\NormalTok{))}
\FunctionTok{table}\NormalTok{(datos}\SpecialCharTok{$}\NormalTok{clasificacion)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##      Caras Economicas  Intemedia 
##        121        792        547
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{set\_entrenamiento }\OtherTok{\textless{}{-}} \FunctionTok{sample\_frac}\NormalTok{(datos, .}\DecValTok{7}\NormalTok{)}
\NormalTok{set\_prueba }\OtherTok{\textless{}{-}}\FunctionTok{setdiff}\NormalTok{(datos, set\_entrenamiento)}


\NormalTok{drop }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"LotFrontage"}\NormalTok{, }\StringTok{"Alley"}\NormalTok{, }\StringTok{"MasVnrType"}\NormalTok{, }\StringTok{"MasVnrArea"}\NormalTok{, }\StringTok{"BsmtQual"}\NormalTok{, }\StringTok{"BsmtCond"}\NormalTok{, }\StringTok{"BsmtExposure"}\NormalTok{, }\StringTok{"BsmtFinType1"}\NormalTok{, }\StringTok{"BsmtFinType2"}\NormalTok{, }\StringTok{"Electrical"}\NormalTok{, }\StringTok{"FireplaceQu"}\NormalTok{, }\StringTok{"GarageType"}\NormalTok{, }\StringTok{"GarageYrBlt"}\NormalTok{, }\StringTok{"GarageFinish"}\NormalTok{, }\StringTok{"GarageQual"}\NormalTok{, }\StringTok{"GarageCond"}\NormalTok{, }\StringTok{"PoolQC"}\NormalTok{, }\StringTok{"Fence"}\NormalTok{, }\StringTok{"MiscFeature"}\NormalTok{)}
\NormalTok{set\_entrenamiento }\OtherTok{\textless{}{-}}\NormalTok{ set\_entrenamiento[, }\SpecialCharTok{!}\NormalTok{(}\FunctionTok{names}\NormalTok{(set\_entrenamiento) }\SpecialCharTok{\%in\%}\NormalTok{ drop)]}
\NormalTok{set\_prueba }\OtherTok{\textless{}{-}}\NormalTok{ set\_prueba[, }\SpecialCharTok{!}\NormalTok{(}\FunctionTok{names}\NormalTok{(set\_prueba) }\SpecialCharTok{\%in\%}\NormalTok{ drop)]}
\end{Highlighting}
\end{Shaded}

Consideramos una casa que valga menos de 170,000 dólares es económica,
si vale entre 171,000 y 289,000 dólares es de un valor intermedio, y si
vale más de 290,000 es una casa cara, esto lo decidiemos teniendo en
cuenta los estándares económicos en Estados Unidos. Se puede observar
que en nuestros datos con dichos parámetros hay más casas consideradas
económicas (792) que intermedias(547) y hay una gran diferencia entre
estas y la cantidad de casas caras(121).

\hypertarget{elabore-un-uxe1rbol-de-clasificaciuxf3n-utilizando-la-variable-respuesta-que-creuxf3-en-el-punto-anterior.-explique-los-resultados-a-los-que-llega.-muestre-el-modelo-gruxe1ficamente.-recuerde-que-la-nueva-variable-respuesta-es-categuxf3rica-pero-se-generuxf3-a-partir-de-los-precios-de-las-casas-no-incluya-el-precio-de-venta-para-entrenar-el-modelo.}{%
\subsubsection{7. Elabore un árbol de clasificación utilizando la
variable respuesta que creó en el punto anterior. Explique los
resultados a los que llega. Muestre el modelo gráficamente. Recuerde que
la nueva variable respuesta es categórica, pero se generó a partir de
los precios de las casas, no incluya el precio de venta para entrenar el
modelo.}\label{elabore-un-uxe1rbol-de-clasificaciuxf3n-utilizando-la-variable-respuesta-que-creuxf3-en-el-punto-anterior.-explique-los-resultados-a-los-que-llega.-muestre-el-modelo-gruxe1ficamente.-recuerde-que-la-nueva-variable-respuesta-es-categuxf3rica-pero-se-generuxf3-a-partir-de-los-precios-de-las-casas-no-incluya-el-precio-de-venta-para-entrenar-el-modelo.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{arbol\_4 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(}\AttributeTok{formula =}\NormalTok{ clasificacion }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_entrenamiento)}
\NormalTok{arbol\_4}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## n= 1022 
## 
## node), split, n, loss, yval, (yprob)
##       * denotes terminal node
## 
## 1) root 1022 464 Economicas (0.0851272 0.5459883 0.3688845)  
##   2) SalePrice< 170500 558   0 Economicas (0.0000000 1.0000000 0.0000000) *
##   3) SalePrice>=170500 464  87 Intemedia (0.1875000 0.0000000 0.8125000)  
##     6) SalePrice>=291538.5 87   0 Caras (1.0000000 0.0000000 0.0000000) *
##     7) SalePrice< 291538.5 377   0 Intemedia (0.0000000 0.0000000 1.0000000) *
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rpart.plot}\NormalTok{(arbol\_4)}
\end{Highlighting}
\end{Shaded}

\includegraphics{ArbolesDeDecision_files/figure-latex/unnamed-chunk-16-1.pdf}
El siguiente diagrama nos indica que las casas económicas conforman el
54\% de los datos de entrenamiento, mientras que las intermedias son el
38\% y las caras unicamente el 8\%.

\hypertarget{utilice-el-modelo-con-el-conjunto-de-prueba-y-determine-la-eficiencia-del-algoritmo-para-clasificar.}{%
\subsubsection{8. Utilice el modelo con el conjunto de prueba y
determine la eficiencia del algoritmo para
clasificar.}\label{utilice-el-modelo-con-el-conjunto-de-prueba-y-determine-la-eficiencia-del-algoritmo-para-clasificar.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{set\_prueba }\OtherTok{\textless{}{-}}\NormalTok{ set\_prueba[, }\SpecialCharTok{!}\NormalTok{(}\FunctionTok{names}\NormalTok{(set\_prueba) }\SpecialCharTok{\%in\%}\NormalTok{ drop)]}
\NormalTok{arbol\_5 }\OtherTok{\textless{}{-}} \FunctionTok{rpart}\NormalTok{(SalePrice }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ set\_prueba)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rpart.plot}\NormalTok{(arbol\_5)}
\end{Highlighting}
\end{Shaded}

\includegraphics{ArbolesDeDecision_files/figure-latex/unnamed-chunk-18-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{predicciones }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(arbol\_5, }\AttributeTok{newdata =}\NormalTok{ set\_prueba)}
\NormalTok{error }\OtherTok{\textless{}{-}} \FunctionTok{abs}\NormalTok{(predicciones }\SpecialCharTok{{-}}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}
\NormalTok{eficiencia }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(error }\SpecialCharTok{/}\NormalTok{ set\_prueba}\SpecialCharTok{$}\NormalTok{SalePrice)}
\NormalTok{eficiencia}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8605103
\end{verbatim}

La eficiencia del modelo se puede considerar aceptable, con un margen de
eror de 0.14. Se puede obsercar que a comparación de la clasifiación
anterior, hay un error de 1\% más en las casas caras que las
económicas/intermedias.

\hypertarget{haga-un-anuxe1lisis-de-la-eficiencia-del-algoritmo-usando-una-matriz-de-confusiuxf3n-para-el-uxe1rbol-de-clasificaciuxf3n.-tenga-en-cuenta-la-efectividad-donde-el-algoritmo-se-equivocuxf3-muxe1s-donde-se-equivocuxf3-menos-y-la-importancia-que-tienen-los-errores.}{%
\subsubsection{9. Haga un análisis de la eficiencia del algoritmo usando
una matriz de confusión para el árbol de clasificación. Tenga en cuenta
la efectividad, donde el algoritmo se equivocó más, donde se equivocó
menos y la importancia que tienen los
errores.}\label{haga-un-anuxe1lisis-de-la-eficiencia-del-algoritmo-usando-una-matriz-de-confusiuxf3n-para-el-uxe1rbol-de-clasificaciuxf3n.-tenga-en-cuenta-la-efectividad-donde-el-algoritmo-se-equivocuxf3-muxe1s-donde-se-equivocuxf3-menos-y-la-importancia-que-tienen-los-errores.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cfm }\OtherTok{\textless{}{-}} \FunctionTok{confusionMatrix}\NormalTok{(}\FunctionTok{table}\NormalTok{(testCompleto}\SpecialCharTok{$}\NormalTok{predRF, testCompleto}\SpecialCharTok{$}\NormalTok{Estado))}
\NormalTok{cfm}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##             
##              Cara Economica Intermedio
##   Cara        160         1         12
##   Economica     4        72         18
##   Intermedio   16        12         55
## 
## Overall Statistics
##                                           
##                Accuracy : 0.82            
##                  95% CI : (0.7757, 0.8588)
##     No Information Rate : 0.5143          
##     P-Value [Acc > NIR] : <2e-16          
##                                           
##                   Kappa : 0.7111          
##                                           
##  Mcnemar's Test P-Value : 0.3116          
## 
## Statistics by Class:
## 
##                      Class: Cara Class: Economica Class: Intermedio
## Sensitivity               0.8889           0.8471            0.6471
## Specificity               0.9235           0.9170            0.8943
## Pos Pred Value            0.9249           0.7660            0.6627
## Neg Pred Value            0.8870           0.9492            0.8876
## Prevalence                0.5143           0.2429            0.2429
## Detection Rate            0.4571           0.2057            0.1571
## Detection Prevalence      0.4943           0.2686            0.2371
## Balanced Accuracy         0.9062           0.8820            0.7707
\end{verbatim}

La diagonal principal de la matriz indica la cantidad de instancias
correctamente clasificadas para cada clase, mientras que los elementos
fuera de la diagonal indican los errores de clasificación. Por ejemplo,
en la clase ``Cara'', de las 173 instancias en el conjunto de prueba,
160 fueron clasificadas correctamente y 13 fueron clasificadas
incorrectamente, 1 de ellas como ``Economica'' y 12 como ``Intermedio''.

En términos de métricas de evaluación, la precisión global del modelo es
de 0.82, lo que indica que el modelo clasificó correctamente el 82\% de
las instancias en el conjunto de prueba. La sensibilidad, que mide la
capacidad del modelo para detectar instancias de cada clase, varía para
cada clase y es mayor para la clase ``Cara'' con un valor de 0.8889 y
menor para la clase ``Intermedio'' con un valor de 0.6471. La
especificidad, que mide la capacidad del modelo para clasificar
correctamente instancias negativas, es alta para todas las clases, lo
que indica que el modelo es bueno en la identificación de instancias que
no pertenecen a cada clase.

La importancia de los errores también puede evaluarse a través de las
métricas de valor predictivo positivo (PPV) y valor predictivo negativo
(NPV). Estas métricas miden la proporción de instancias correctamente
clasificadas entre las instancias clasificadas en una clase específica.
En este caso, el PPV es más alto para la clase ``Cara'' con un valor de
0.9249, lo que indica que el modelo clasificó correctamente la mayoría
de las instancias predichas como ``Cara''. Por otro lado, el PPV es más
bajo para la clase ``Economica'' con un valor de 0.7660, lo que indica
que el modelo cometió más errores al clasificar instancias como
``Economica''.

\hypertarget{entrene-un-modelo-usando-validaciuxf3n-cruzada-prediga-con-uxe9l.-le-fue-mejor-que-al-modelo-anterior}{%
\subsubsection{10. Entrene un modelo usando validación cruzada, prediga
con él. ¿le fue mejor que al modelo
anterior?}\label{entrene-un-modelo-usando-validaciuxf3n-cruzada-prediga-con-uxe9l.-le-fue-mejor-que-al-modelo-anterior}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(mlbench)}
\NormalTok{folds }\OtherTok{\textless{}{-}} \FunctionTok{createFolds}\NormalTok{(set\_entrenamiento}\SpecialCharTok{$}\NormalTok{SalePrice, }\AttributeTok{k =} \DecValTok{10}\NormalTok{)}


\CommentTok{\#cvDecisionTree \textless{}{-} lapply(folds, function(x)\{}
\CommentTok{\# training\_fold \textless{}{-} training\_set[{-}x, ]}
\CommentTok{\#  test\_fold \textless{}{-} training\_set[x, ]}
\CommentTok{\#  clasificador \textless{}{-} rpart(SalePrice \textasciitilde{} ., data = training\_fold)}
\CommentTok{\#  y\_pred \textless{}{-} predict(clasificador, newdata = test\_fold, type = \textquotesingle{}class\textquotesingle{})}
\CommentTok{\#  cm \textless{}{-} table(test\_fold$SalePrice, y\_pred)}
  \CommentTok{\#precision \textless{}{-} (cm[1,1] + cm[2,2]) / (cm[1,1] + cm[2,2] +cm[1,2] + cm[2,1])}
  \CommentTok{\#return(precision)}
\CommentTok{\#\})}


\FunctionTok{data}\NormalTok{(}\StringTok{"PimaIndiansDiabetes"}\NormalTok{)}


\NormalTok{entrenamiento\_index }\OtherTok{\textless{}{-}} \FunctionTok{createDataPartition}\NormalTok{(PimaIndiansDiabetes}\SpecialCharTok{$}\NormalTok{diabetes, }\AttributeTok{p =} \FloatTok{0.7}\NormalTok{, }\AttributeTok{list =} \ConstantTok{FALSE}\NormalTok{) }\CommentTok{\#70 entrenamiento, 30 prueba}
\NormalTok{entrenamiento }\OtherTok{\textless{}{-}}\NormalTok{ PimaIndiansDiabetes[entrenamiento\_index, ]}
\NormalTok{pruebas }\OtherTok{\textless{}{-}}\NormalTok{ PimaIndiansDiabetes[}\SpecialCharTok{{-}}\NormalTok{entrenamiento\_index, ]}

\NormalTok{f }\OtherTok{\textless{}{-}}\NormalTok{ diabetes }\SpecialCharTok{\textasciitilde{}}\NormalTok{ .}

\NormalTok{m1 }\OtherTok{\textless{}{-}} \FunctionTok{train}\NormalTok{(f, }\AttributeTok{data =}\NormalTok{ entrenamiento, }\AttributeTok{method =} \StringTok{"glm"}\NormalTok{, }\AttributeTok{trControl =} \FunctionTok{trainControl}\NormalTok{(}\AttributeTok{method =} \StringTok{"cv"}\NormalTok{, }\AttributeTok{number =} \DecValTok{10}\NormalTok{))}

\NormalTok{pred }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(m1, }\AttributeTok{newdata =}\NormalTok{ pruebas)}

\NormalTok{rendimiento }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(pred }\SpecialCharTok{==}\NormalTok{ pruebas}\SpecialCharTok{$}\NormalTok{diabetes)}
\end{Highlighting}
\end{Shaded}

Se puede observar que el modelo posee un buen rendimiento \#\#\# 11.
Haga al menos, 3 modelos más cambiando la profundidad del árbol. ¿Cuál
funcionó mejor?

\hypertarget{repite-los-anuxe1lisis-usando-random-forest-como-algoritmo-de-predicciuxf3n-explique-sus-resultados-comparando-ambos-algoritmos.}{%
\subsubsection{12. Repite los análisis usando random forest como
algoritmo de predicción, explique sus resultados comparando ambos
algoritmos.}\label{repite-los-anuxe1lisis-usando-random-forest-como-algoritmo-de-predicciuxf3n-explique-sus-resultados-comparando-ambos-algoritmos.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cfmRandomForest }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(testCompleto}\SpecialCharTok{$}\NormalTok{predRF, testCompleto}\SpecialCharTok{$}\NormalTok{Estado)}
\FunctionTok{plot}\NormalTok{(cfmRandomForest);}\FunctionTok{text}\NormalTok{(cfmRandomForest)}
\end{Highlighting}
\end{Shaded}

\includegraphics{ArbolesDeDecision_files/figure-latex/unnamed-chunk-23-1.pdf}

La matriz de confusión del modelo de Random Forest muestra una mayor
precisión en la predicción de las clases en comparación con el árbol de
decisión. La precisión global del modelo Random Forest es del 90.3\%,
mientras que la precisión global del árbol de decisión es del 82\%.
Además, el modelo Random Forest tiene una mayor sensibilidad y
especificidad en la predicción de cada clase, lo que indica que es mejor
para detectar tanto verdaderos positivos como verdaderos negativos. En
general, se puede concluir que el modelo Random Forest es más preciso en
la predicción de la variable objetivo en comparación con el árbol de
decisión.

\end{document}
